In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score
# We will visualize the messages with a word cloud
from wordcloud import WordCloud

# Multinomial Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB

# Import Tf-idf Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Import the Label Encoder
from sklearn.preprocessing import LabelEncoder

%matplotlib inline

In [2]:
# We want to see whole content (non-truncated)
pd.set_option('display.max_colwidth', None)

In [3]:
Kids_first = pd.read_csv(r'C:\Users\Ray\Desktop\Kids_first_processed.csv',encoding='latin-1')
Kids_first.head()

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   

                                                                                                                                                 Text message  \
0                                                                     Doesn't g have class early tomorrow and thus shouldn't be trying to smoke at  &lt;#&gt;   
1      Superb Thought- \Be grateful that u dont have everything u want. That means u still have an opportunity to be happier tomorrow than u are today.\":-)"   
2                                                                                                           Hope you are having a good week. Just checking in   
3  I'm used to it. I just hope my agents don't drop me since i've only booked a few things this year. This whole me in boston, them in nyc was an experiment.   
4                                                                                                    Thursday night? Yeah, sure thing, we'll work it out then   

                                                                                                         Processed  \
0                                                        ['class', 'early', 'tomorrow', 'thus', 'trying', 'smoke']   
1       ['superb', 'grateful', 'dont', 'everything', 'want', 'means', 'still', 'opportunity', 'happy', 'tomorrow']   
2                                                                             ['hope', 'good', 'week', 'checking']   
3  ['used', 'hope', 'agents', 'drop', 'since', 'booked', 'things', 'year', 'whole', 'boston', 'nyc', 'experiment']   
4                                                           ['thursday', 'night', 'yeah', 'sure', 'thing', 'work']   

   Polarity  Subjectivity     Label  
0       0.1      0.300000  positive  
1       0.9      1.000000  positive  
2       0.7      0.600000  positive  
3       0.2      0.400000  positive  
4       0.5      0.888889  positive

In [4]:
# Select the features and the target
X =Kids_first ['Text message']
y = Kids_first['Label']


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=25, stratify=y)

In [6]:
# Create the tf-idf vectorizer
vectorizer = TfidfVectorizer(strip_accents='ascii')

# First fit the vectorizer with our training set
tfidf_train = vectorizer.fit_transform(X_train)

# Now we can fit our test data with the same vectorizer
tfidf_test = vectorizer.transform(X_test)

In [7]:
# Initialize the Multinomial Naive Bayes classifier
nb = MultinomialNB()

# Fit the model
nb.fit(tfidf_train, y_train)

# Print the accuracy score
print("Accuracy:",nb.score(tfidf_test, y_test))

Accuracy: 0.6440677966101694


In [10]:

# Predict the labels
y_pred = nb.predict(tfidf_test)

# Print the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n")
print(cm)

# Print the Classification Report
cr = classification_report(y_test, y_pred)
print("\n\nClassification Report\n")
print(cr)

# Get probabilities.
y_pred_proba = nb.predict(tfidf_test)


Confusion Matrix

[[ 0 20  2]
 [ 0 49  5]
 [ 0 15 27]]


Classification Report

              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        22
     Neutral       0.58      0.91      0.71        54
    positive       0.79      0.64      0.71        42

    accuracy                           0.64       118
   macro avg       0.46      0.52      0.47       118
weighted avg       0.55      0.64      0.58       118



C:\Users\Ray\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ray\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ray\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
